### ISSUE TITLE
Are the human-readable messages constant as part of the public API?

### ISSUE THREAD

**Issue by anko** [estools/esvalid#49]
I'm writing [a program](https://github.com/anko/eslisp) that only needs to check for validity of an AST _subtree_, so I'm [using `esvalid.errors(partOfAst)` and stripping all errors with the message "_given AST node should be of type Program_"](https://github.com/anko/eslisp/blob/755e3ac1060be359c1d9acb3306ffb911c8370ff/src/translate.ls#L202-L204). I've pinned esvalid as a specific version, because I'm unsure whether that's part of the public API.

Is it? Might that human-readable message change in the future?

If I've correctly understood, #33 plans to introduce machine-readable identifiers for the specific error types, which might be a better way to solve this.

**Comment by michaelficarra** [comment]
You've understood correctly. The messages are strictly for human consumption, and may change arbitrarily in a patch release. If you'd like the functionality that you've described, someone will need to implement #33. Before doing all that work, however, it would be great to update this with ES6 support. There are many more validations we need to make. For instance, the only valid MetaProperty node has a `meta` of `{type: "Identifier", name: "new"}` and a `property` of `{type: "Identifier", name: "target"}`.

**Comment by anko** [comment]
Closing in favour of #33.
